// import "./search-form";
// import "./render-trandFilms";
// import "./footer-modal";
// import "./local-storage";
// import "./modal";
// import "./pagination";
// import "./movie-card-listener";
// import "./render-watch-queue";
// import "./button-up";
// import "./header-library_buttons";
// import "./render-my-library";
// import "./refs";

import "./search-form";
import "./render/render-trandFilms";
import "./footer-modal";
import "./local-storage";
import "./modal";
import "./pagination";
import "./movie-card-listener";
import "./render/render-watch-queue";
import "./button-up";
import "./header-library_buttons";
import "./render/render-my-library";
import "./refs/refs";