const refs={
    container:document.querySelector('#tui-pagination-container'),
    movieTrand:document.querySelector('.movie-cards'),
    loader:document.querySelector('.loader'),
    form:document.querySelector('#search-form'),
    movieTrand:document.querySelector('.movie-cards'),
    movieContainer:document.querySelector('.movie-cards'),
    btnWatched:document.querySelector('.btn-watched'),
    btnQueue:document.querySelector('.btn-queue'),
    btnMyLibrary:document.querySelector('.library_button'),
    filmContainer:document.querySelector('.movie-cards'),
    modalConteiner: document.querySelector('.modal-conteiner'),
    closeModalBtn: document.querySelector('.close-modal'),
    backdrop: document.querySelector('.js-backdrop'),
    btnAddToWatched:document.querySelector('.modal-add-watched'),
    btnAddToQueue:document.querySelector('.modal-add-queue'),
    watchedButton:document.querySelector('.watched_button'),
    queueButton:document.querySelector('.queue_button'),
    libraryButton:document.querySelector('.library_button'),
    homeButton:document.querySelector('.home_button'),
    form:document.querySelector('.search-form'),
    headerOrange:document.querySelector('.header'),
    buttomLibrary:document.querySelector('.headermenu__buttons'),
    buttomLibW:document.querySelector('.btnW'),
    buttomLibQ:document.querySelector('.btnQ'),
    divLibraryButtons:document.querySelector('.library__buttons'),
}
export default refs